sensors:
  prox_1:
    type: proximity_sensor
    pose:
      xyz: [0.2, 2.8, 0.885]
      rpy: [0, 0, 'pi']
  prox_2:
    type: proximity_sensor
    pose:
      xyz: [-0.2, 2.8, 0.885]
      rpy: [0, 0, 0]
  logical_camera_belt:
    type: logical_camera
    pose:
      xyz: [0, 2, 1.9]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock1:
    type: logical_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock2:
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock3:
    type: logical_camera
    pose:
      xyz: [3.082385, -1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock4:
    type: logical_camera
    pose:
      xyz: [5, -1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock5:
    type: logical_camera
    pose:
      xyz: [-3.748, 0, 2.45]
      rpy: [0, 'pi/2', 'pi/2']
  logical_camera_stock6:
    type: logical_camera
    pose:
      xyz: [-3.748, 3, 2.45]
      rpy: [0, 'pi/2', 'pi/2']
